# Generated by Django 3.2.dev20200624102636 on 2020-07-05 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_postgres_unlimited_varchar


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotUsedPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UrlToProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShildToProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('to_delete', models.BooleanField(default=False)),
                ('founded_cnt', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShildFromURLText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.urltoprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ShildFromNotUsedPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.notusedpaper')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('text', django_postgres_unlimited_varchar.UnlimitedCharField()),
                ('uniquenessPercent', models.FloatField(default=-1)),
                ('truth', models.FloatField(default=-1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notusedpaper',
            name='paper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.paper'),
        ),
        migrations.CreateModel(
            name='AddPaperConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('name', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('check_url_cnt', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
