# Generated by Django 3.2.dev20200624102636 on 2020-07-05 14:19

from django.db import migrations, models
import django.db.models.deletion
import django_postgres_unlimited_varchar


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_urltoprocess_flg_process_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShildFromURLText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('url', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.urltoprocess')),
            ],
        ),
    ]
