# Generated by Django 3.2.dev20200624102636 on 2020-07-01 10:01

from django.db import migrations
import django_postgres_unlimited_varchar


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200629_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='shilds',
            field=django_postgres_unlimited_varchar.UnlimitedCharField(default=''),
        ),
    ]
