# Generated by Django 3.2.dev20200624102636 on 2020-07-02 14:00

from django.db import migrations, models
import django_postgres_unlimited_varchar


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_paper_shilds'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='name',
            field=django_postgres_unlimited_varchar.UnlimitedCharField(default=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='thruth',
            field=models.FloatField(default=-1),
        ),
    ]
