# Generated by Django 3.2.dev20200624102636 on 2020-07-05 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_postgres_unlimited_varchar


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_shildfromurltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='shildfromurltext',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShildFromNotUsedPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.notusedpaper')),
            ],
        ),
    ]
