# Generated by Django 3.2.dev20200624102636 on 2020-07-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_thruth_paper_truth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='shilds',
        ),
    ]
