# Generated by Django 3.2.dev20200624102636 on 2020-07-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_paper_shilds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
