# Generated by Django 3.2.dev20200624102636 on 2020-07-04 20:17

from django.db import migrations, models
import django_postgres_unlimited_varchar


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPaperConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_shild', models.IntegerField(default=0)),
                ('text', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('name', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ShildToProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
                ('to_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UrlToProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', django_postgres_unlimited_varchar.UnlimitedCharField(default='')),
            ],
        ),
    ]
