# Generated by Django 3.2.dev20200624102636 on 2020-07-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_addpaperconf_shildtoprocess_urltoprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urltoprocess',
            old_name='val',
            new_name='value',
        ),
    ]
