# Generated by Django 3.2.dev20200624102636 on 2020-07-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_val_urltoprocess_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shildtoprocess',
            old_name='val',
            new_name='value',
        ),
    ]
