# Generated by Django 3.2.dev20200624102636 on 2020-07-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_val_shildtoprocess_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpaperconf',
            name='current_shild',
        ),
    ]
