# Generated by Django 3.2.dev20200624102636 on 2020-07-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_addpaperconf_current_shild'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShildToProcess',
            new_name='ShildToProcess2',
        ),
    ]
