# Generated by Django 3.2.dev20200624102636 on 2020-07-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_shildtoprocess_shildtoprocess2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShildToProcess2',
            new_name='ShildToProcess',
        ),
    ]
